displayName: Returns Agent
schemaName: cr915_returnsAgent
accessControlPolicy: ChatbotReaders
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  settings:
    GenerativeActionsEnabled: true

  gPTSettings:
    defaultSchemaName: cr915_returnsAgent.gpt.default

  aISettings:
    useModelKnowledge: false
    isFileAnalysisEnabled: false
    isSemanticSearchEnabled: false

  recognizer:
    kind: GenerativeAIRecognizer

template: default-2.1.0
language: 1033